name: Refresh Airthings Token

on:
  schedule:
    - cron: "*/50 * * * *"  # Runs every 50 minutes
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script to refresh the token
      - name: Refresh token
        env:
          AIRTHINGS_CLIENT_ID: ${{ secrets.AIRTHINGS_CLIENT_ID }}
          AIRTHINGS_CLIENT_SECRET: ${{ secrets.AIRTHINGS_CLIENT_SECRET }}
        run: python refresh_token.py

      # Commit and push the updated token file
      - name: Commit and push token file
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@noreply.github.com"
          git add airthings_token.json
          git commit -m "Update Airthings token" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
